### ISSUE TITLE
re: readme

### ISSUE THREAD

**Issue by wizzard0** [gildas-lormeau/SingleFile-MV3#1] opened 2021-09-27 13:07 UTC
So cool! So many improvements!

Speaking a bit more seriously, how did they manage to break the `Blob`s? Sounds crazy

**Comment by gildas-lormeau** [comment] 2021-09-27 13:20
Thanks! 

Actually, they broke the ability to create a Blob URL with `URL.createObjectURL()`. This feature is not available in Service Workers. The regressions introduced with Service Workers (used as background scripts) are documented here: https://github.com/w3c/webextensions/issues/72.

**Comment by wizzard0** [comment] 2021-09-27 17:05
Ugh. I can see the rationale, but that's an awful lot of crippling changes. I wonder how long before we'll see Chrome forks keeping manifest V2.

**Comment by d-damien** [comment] 2022-10-03 07:37
Standard SingleFile will still be maintained ?

**Comment by gildas-lormeau** [comment] 2022-10-03 10:12
Yes, I confirm it will still be maintained but it will run only in Firefox.

**Comment by gildas-lormeau** [comment] 2023-10-27 23:01
I'm closing this issue because almost all the issues have been fixed or circumvented, 2 years later...

**Closed by gildas-lormeau** 2023-10-27 23:01 UTC
